spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  # data:
  #   mongodb:
  #     uri: mongodb://admin:admin123@localhost:27017/userdb?authSource=admin
  #     database: userdb

  # datasource:
  #   url: jdbc:postgresql://localhost:5432/userdb
  #   username: postgres
  #   password: postgres

  # jpa:
  #   database: POSTGRESQL
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create-drop
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driverClassName: org.h2.Driver
  #   username: sa
  #   password:
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create

server:
  port: 8082
