spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # datasource:
  #   url: jdbc:h2:mem:product-db
  #   username: sa
  #   password:
  #   driver-class-name: org.h2.Driver
  # h2:
  #   console:
  #     enabled: true
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create
server:
  port: 8081
