spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console

  # datasource:
  #   url: jdbc:h2:mem:orderdb
  #   driverClassName: org.h2.Driver
  #   username: sa
  #   password:

  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: create-drop

server:
  port: 8083
