services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      - POSTGRES_DB=ecommercedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./data/teste-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        labels: "postgres"
        env: "postgres"
